name: js_mimicry
version: 0.2.1+2
author: Igor Demyanov <igor.demyanov@gmail.com>
description: |-
  Allows the use of Dart classes and objects in javascript.
  Generates a special proxy classes.
homepage: https://github.com/DisDis/jsMimicry
environment:
  sdk: '>=1.9.3'
dependencies:
  analyzer: '>=0.23.0 <0.27.0'
  path: '>=1.3.5 <2.0.0'
  code_transformers: '>=0.2.0 <0.3.0'
  dom_stub: '>=0.0.1 <0.1.0'
#    git:
#          url: https://github.com/DisDis/dom_stub
#    path: ../dom-stub
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  barback: any
  browser: any
transformers:
 - js_mimicry
 - dom_stub
 - test/pub_serve:
    $include: test/**_test{.*,}.dart