name: js_mimicry
version: 0.0.2
author: Igor Demyanov <igor.demyanov@gmail.com>
description: |-
  Allows the use of Dart classes and objects in javascript.
  Generates a special proxy classes.
homepage: https://github.com/DisDis/jsMimicry
environment:
  sdk: '>=1.9.3'
dependencies:
  analyzer: '>=0.25.0'
  path: '>=1.3.5 <2.0.0'
  code_transformers: any
dev_dependencies:
  barback: any
  browser: any
  smoke: any
transformers:
 - js_mimicry/transformer2
 - js_mimicry
