name: js_mimicry
version: 0.0.1+4
author: Igor Demyanov <igor.demyanov@gmail.com>
description: |-
  Allows the use of Dart classes and objects in javascript.
  Generates a special proxy classes.
homepage: https://github.com/DisDis/jsMimicry
environment:
  sdk: '>1.4.0'
dependencies:
  analyzer: '>=0.22.4 <0.23.0'
  path: '>=1.3.0 <2.0.0'
dev_dependencies:
  barback: any
  browser: any
