name: js_mimicry
version: 2.0.0
author: Igor Demyanov <igor.demyanov@gmail.com>
description: |-
  Allows the use of Dart classes and objects in javascript.
  Generates a special proxy classes.
homepage: https://github.com/DisDis/jsMimicry
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  path: '>=1.3.5 <2.0.0'
  build: ^0.12.7
  build_resolvers: ^0.2.1
  build_runner: ^0.10.0
  build_test: ^0.10.0
#  dom_stub: '>=0.0.1 <0.1.0'
#    git:
#          url: https://github.com/DisDis/dom_stub
#    path: ../dom-stub
dev_dependencies:
  test: 1.3.0
